package cmd

import (
	"bytes"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/kidoz/zabbix-threat-control-go/internal/config"
)

var (
	migrateInput  string
	migrateOutput string
)

var migrateCmd = &cobra.Command{
	Use:   "migrate-config",
	Short: "Convert legacy INI config to YAML format",
	Long: `Read a legacy INI-format ztc.conf (from the original Python
zabbix-threat-control) and write the equivalent YAML config file.

This lets you migrate from the old config format to the new one
while preserving all settings.

Examples:
  # Print YAML to stdout
  ztc migrate-config

  # Write to a specific file
  ztc migrate-config --output /etc/ztc.yaml

  # Specify a custom input path
  ztc migrate-config --input /opt/monitoring/zabbix-threat-control/ztc.conf --output /etc/ztc.yaml`,
	RunE: func(cmd *cobra.Command, args []string) error {
		cfg, warnings, err := config.LoadINIWithWarnings(migrateInput)
		if err != nil {
			return fmt.Errorf("failed to read INI config: %w", err)
		}

		for _, w := range warnings {
			fmt.Fprintf(os.Stderr, "WARNING: %s\n", w)
		}
		if len(warnings) > 0 {
			fmt.Fprintf(os.Stderr, "%d unrecognized INI key(s) skipped\n", len(warnings))
		}

		yamlBytes, err := renderYAML(cfg)
		if err != nil {
			return fmt.Errorf("failed to render YAML: %w", err)
		}

		if migrateOutput == "" || migrateOutput == "-" {
			_, err := os.Stdout.Write(yamlBytes)
			return err
		}

		if err := os.WriteFile(migrateOutput, yamlBytes, 0600); err != nil {
			return fmt.Errorf("failed to write %s: %w", migrateOutput, err)
		}
		fmt.Fprintf(os.Stderr, "Config written to %s\n", migrateOutput)
		return nil
	},
}

func init() {
	migrateCmd.Flags().StringVar(&migrateInput, "input", config.DefaultConfigPath, "path to legacy INI config")
	migrateCmd.Flags().StringVar(&migrateOutput, "output", "", "output YAML path (default: stdout)")
	rootCmd.AddCommand(migrateCmd)
}

// renderYAML produces a human-friendly YAML representation of the config.
// We write it manually to preserve comments and ordering.
func renderYAML(cfg *config.Config) ([]byte, error) {
	var buf bytes.Buffer
	defaults := config.DefaultConfig()

	buf.WriteString("# Zabbix Threat Control Configuration\n")
	buf.WriteString("# Generated by: ztc migrate-config\n\n")

	buf.WriteString("zabbix:\n")
	writeStr(&buf, "  ", "front_url", cfg.Zabbix.FrontURL, defaults.Zabbix.FrontURL)
	buf.WriteString(fmt.Sprintf("  api_user: %s\n", yamlQuote(cfg.Zabbix.APIUser)))
	buf.WriteString(fmt.Sprintf("  api_password: %s\n", yamlQuote(cfg.Zabbix.APIPassword)))
	writeStr(&buf, "  ", "server_fqdn", cfg.Zabbix.ServerFQDN, defaults.Zabbix.ServerFQDN)
	writeInt(&buf, "  ", "server_port", cfg.Zabbix.ServerPort, defaults.Zabbix.ServerPort)
	writeStr(&buf, "  ", "sender_path", cfg.Zabbix.SenderPath, defaults.Zabbix.SenderPath)
	writeStr(&buf, "  ", "get_path", cfg.Zabbix.GetPath, defaults.Zabbix.GetPath)
	writeBool(&buf, "  ", "verify_ssl", cfg.Zabbix.VerifySSL, defaults.Zabbix.VerifySSL)

	buf.WriteString("\nvulners:\n")
	buf.WriteString(fmt.Sprintf("  api_key: %s\n", yamlQuote(cfg.Vulners.APIKey)))
	writeStr(&buf, "  ", "host", cfg.Vulners.Host, defaults.Vulners.Host)
	writeInt(&buf, "  ", "rate_limit", cfg.Vulners.RateLimit, defaults.Vulners.RateLimit)

	buf.WriteString("\nscan:\n")
	writeFloat(&buf, "  ", "min_cvss", cfg.Scan.MinCVSS, defaults.Scan.MinCVSS)
	writeStr(&buf, "  ", "os_report_template", cfg.Scan.OSReportTemplate, defaults.Scan.OSReportTemplate)
	writeNonDefault(&buf, "  ", "os_report_visible_name", cfg.Scan.OSReportVisibleName, defaults.Scan.OSReportVisibleName)
	writeNonDefault(&buf, "  ", "template_group_name", cfg.Scan.TemplateGroupName, defaults.Scan.TemplateGroupName)
	writeInt(&buf, "  ", "timeout", cfg.Scan.Timeout, defaults.Scan.Timeout)
	writeInt(&buf, "  ", "workers", cfg.Scan.Workers, defaults.Scan.Workers)
	writeIntNonDefault(&buf, "  ", "lld_delay", cfg.Scan.LLDDelay, defaults.Scan.LLDDelay)

	buf.WriteString("\ntelemetry:\n")
	writeBool(&buf, "  ", "enabled", cfg.Telemetry.Enabled, defaults.Telemetry.Enabled)
	writeStr(&buf, "  ", "otlp_endpoint", cfg.Telemetry.OTLPEndpoint, defaults.Telemetry.OTLPEndpoint)

	// Only render naming section if any value differs from defaults
	n := cfg.Naming
	d := defaults.Naming
	if n != d {
		buf.WriteString("\nnaming:\n")
		writeNonDefault(&buf, "  ", "hosts_host", n.HostsHost, d.HostsHost)
		writeNonDefault(&buf, "  ", "hosts_visible_name", n.HostsVisibleName, d.HostsVisibleName)
		writeNonDefault(&buf, "  ", "packages_host", n.PackagesHost, d.PackagesHost)
		writeNonDefault(&buf, "  ", "packages_visible_name", n.PackagesVisibleName, d.PackagesVisibleName)
		writeNonDefault(&buf, "  ", "bulletins_host", n.BulletinsHost, d.BulletinsHost)
		writeNonDefault(&buf, "  ", "bulletins_visible_name", n.BulletinsVisibleName, d.BulletinsVisibleName)
		writeNonDefault(&buf, "  ", "statistics_host", n.StatisticsHost, d.StatisticsHost)
		writeNonDefault(&buf, "  ", "statistics_visible_name", n.StatisticsVisibleName, d.StatisticsVisibleName)
		writeNonDefault(&buf, "  ", "group_name", n.GroupName, d.GroupName)
		writeNonDefault(&buf, "  ", "dashboard_name", n.DashboardName, d.DashboardName)
		writeNonDefault(&buf, "  ", "action_name", n.ActionName, d.ActionName)
	}

	return buf.Bytes(), nil
}

func writeStr(buf *bytes.Buffer, indent, key, val, _ string) {
	fmt.Fprintf(buf, "%s%s: %s\n", indent, key, yamlQuote(val))
}

// yamlQuote wraps a string in double quotes when it contains characters
// that are unsafe in bare YAML values.
func yamlQuote(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ":#{}&*!|>'\"%@`") ||
		strings.HasPrefix(s, " ") || strings.HasSuffix(s, " ") {
		s = strings.ReplaceAll(s, `\`, `\\`)
		s = strings.ReplaceAll(s, `"`, `\"`)
		return `"` + s + `"`
	}
	return s
}

func writeInt(buf *bytes.Buffer, indent, key string, val, _ int) {
	fmt.Fprintf(buf, "%s%s: %d\n", indent, key, val)
}

func writeBool(buf *bytes.Buffer, indent, key string, val, _ bool) {
	fmt.Fprintf(buf, "%s%s: %v\n", indent, key, val)
}

func writeFloat(buf *bytes.Buffer, indent, key string, val, _ float64) {
	fmt.Fprintf(buf, "%s%s: %g\n", indent, key, val)
}

func writeIntNonDefault(buf *bytes.Buffer, indent, key string, val, defaultVal int) {
	if val != defaultVal {
		fmt.Fprintf(buf, "%s%s: %d\n", indent, key, val)
	}
}

func writeNonDefault(buf *bytes.Buffer, indent, key, val, defaultVal string) {
	if val != defaultVal {
		fmt.Fprintf(buf, "%s%s: %s\n", indent, key, yamlQuote(val))
	}
}
