// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/kidoz/zabbix-threat-control-go/internal/config"
	"github.com/kidoz/zabbix-threat-control-go/internal/fixer"
	"github.com/kidoz/zabbix-threat-control-go/internal/scanner"
	"github.com/kidoz/zabbix-threat-control-go/internal/zabbix"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func initScanner(cfg2 *config.Config, log2 *zap.Logger) (*scanner.Scanner, error) {
	client, err := zabbix.NewClient(cfg2, log2)
	if err != nil {
		return nil, err
	}
	vulnersClient, err := scanner.ProvideVulnersClient(cfg2)
	if err != nil {
		return nil, err
	}
	sender := zabbix.NewSender(cfg2, log2)
	hostMatrix := scanner.NewHostMatrix(cfg2, log2, client)
	aggregator := scanner.NewAggregator()
	namingConfig := scanner.ProvideNamingConfig(cfg2)
	lldGenerator := scanner.NewLLDGenerator(namingConfig)
	scannerScanner := scanner.ProvideScanner(cfg2, log2, client, vulnersClient, sender, hostMatrix, aggregator, lldGenerator)
	return scannerScanner, nil
}

func initFixer(cfg2 *config.Config, log2 *zap.Logger) (*fixer.Fixer, error) {
	client, err := zabbix.NewClient(cfg2, log2)
	if err != nil {
		return nil, err
	}
	executor := fixer.NewExecutor(cfg2, log2)
	fixerFixer := fixer.ProvideFixer(cfg2, log2, client, executor)
	return fixerFixer, nil
}

func initZabbixClient(cfg2 *config.Config, log2 *zap.Logger) (*zabbix.Client, error) {
	client, err := zabbix.NewClient(cfg2, log2)
	if err != nil {
		return nil, err
	}
	return client, nil
}
